FROM python


RUN groupadd -r uwsgi && useradd -r -g uwsgi uwsgi

WORKDIR /yahoo
COPY yahoo /yahoo
COPY yahoo-requirements.txt ./

RUN pip install --upgrade pip
RUN pip install --upgrade setuptools
RUN pip install -r yahoo-requirements.txt

USER root

CMD ["./cmd.sh"]

